services:
  dps-citations-api:
    container_name: dps-citations-api
    restart: always
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - prod-network

networks:
  prod-network:
    external: true
    name: prod-network
