services:
  dps-citations-api:
    container_name: dps-citations-api
    restart: always
    build: .
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
      - node-tls:/node-tls
    networks:
      - prod-network

volumes:
  node-tls:
    external: true
    name: node-tls

networks:
  prod-network:
    external: true
    name: prod-network
